In [1]:
print("hello world")

hello world


In [2]:
a=2
###this is python tutorial


In [3]:
###this

## this is python

In [4]:
import numpy as np

In [5]:
a=[1,2.1,3]

In [6]:
a=np.array(a)

In [7]:
a.dtype

dtype('float64')

In [8]:
a.ndim

1

In [9]:
a=[[1,2,3],[4,5,6]]
a=np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array.shape

NameError: name 'array' is not defined

In [11]:
a.shape


(2, 3)

In [12]:
a = [[1,True,3],[4,5,6]]
a=np.array(a)
a.dtype


dtype('int32')

In [13]:
a.shape

(2, 3)

In [14]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a=np.array.size
a

AttributeError: 'builtin_function_or_method' object has no attribute 'size'

In [15]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a=np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array.shape

NameError: name 'array' is not defined

In [17]:
a.shape

(3, 3)

In [18]:
a[2,2]

9

In [19]:
a[0:1,1:3]

array([[2, 3]])

In [20]:
new=np.array(3,4)

TypeError: Cannot interpret '4' as a data type

In [21]:
digits=np.random.rand(3,4)

In [22]:
digits

array([[0.6669907 , 0.14557564, 0.58794494, 0.40730154],
       [0.55825546, 0.10033161, 0.20112708, 0.40684587],
       [0.97452395, 0.68281807, 0.28977857, 0.99448865]])

In [ ]:
import numpy as np

In [23]:
new_array=np.random.randint(1,11)

In [24]:
new_array

5

In [25]:
new_array=np.random.randint(1,11,(3,4))

In [26]:
new_array

array([[ 6,  6,  3, 10],
       [ 5,  9, 10,  5],
       [ 1,  8,  6,  9]])

# Find the maximum value in the array created in step 1.

In [27]:
new_array=max(new_array)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
new_array=np.max(new_array)

In [29]:
new_array

10

In [30]:
3- Calculate the mean value of each row in the array.
b=np.array(3,4)

SyntaxError: invalid syntax (1156650119.py, line 1)

In [31]:
b=np.array(3,4)

TypeError: Cannot interpret '4' as a data type

In [32]:
b=np.b(3,4)

AttributeError: module 'numpy' has no attribute 'b'

In [33]:
b=np.array(3,4)

TypeError: Cannot interpret '4' as a data type

In [34]:
new_array=np.mean(axis=1)

TypeError: mean() missing 1 required positional argument: 'a'

In [35]:
new_array=np.mean(new_array,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 0

In [36]:
new_array=np.random.randint(1,11,(3,4))

In [37]:
new_array

array([[ 6,  4,  6,  4],
       [ 4,  9, 10,  4],
       [ 4,  4,  2,  3]])

In [38]:
new_array=np.mean(new_array,axis=1)

In [39]:
new_array

array([5.  , 6.75, 3.25])

In [40]:
# Reshape the array from step 1 into a shape of (2, 6).
new_array=np.random.randint(1,11,(3,4))
b=np.reshape(2,6)

ValueError: cannot reshape array of size 1 into shape (6,)

In [41]:
new_array=np.random.randint(1,11,(3,4))
b=np.reshape(new_array,(2,6))

In [42]:
b

array([[ 5, 10, 10,  6,  4,  6],
       [ 4,  7,  4,  8, 10,  1]])

In [43]:
#- Multiply each element in the array by 2.
new_array=np.random.randint(1,11,(3,4))


In [44]:
new_array=new_array*2

In [45]:
new_array

array([[14, 14,  2, 18],
       [ 8, 20, 10,  4],
       [10,  8,  6, 18]])

In [46]:
#- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.

In [47]:
b=np.random.randint(1,11,(3,4))

In [48]:
b

array([[1, 8, 4, 4],
       [9, 9, 2, 2],
       [2, 6, 9, 1]])

In [49]:
b=np.random.randint(0,10,(3,4))

In [50]:
b

array([[9, 2, 3, 2],
       [8, 2, 0, 9],
       [6, 6, 6, 5]])

In [52]:
b%2!=0

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False, False,  True]])

In [54]:
b[b%2!=0]

array([9, 3, 9, 5])

In [55]:
#- Create a 3x3 identity matrix using numpy.

In [59]:
b=np.identity(3,dtype='int32')

In [60]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [61]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [62]:
# create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).


In [68]:
b=np.random.randn(5,5)

In [67]:
b

array([[ 2.10483006, -0.07388191, -0.79299542,  0.63822903,  0.84721253],
       [-0.16816071, -0.10905703,  0.82646021, -0.02902158, -1.4506303 ],
       [ 1.08365791, -0.05587789, -2.0178199 , -1.79102754, -2.36129921],
       [ 0.32082612, -0.24882642,  0.4345832 , -1.77459389,  0.29291342],
       [ 0.37186627, -0.39154722, -0.87611389,  0.04922931, -0.15247309]])

In [73]:
np_mean=np.mean(b)
np_sd=np.std(b)


In [75]:
np_mean


-0.19973143666956378

In [76]:
np_sd

0.84141803665781

In [78]:
(b-np_mean)/np_sd

array([[ 0.55960113, -1.84676944, -0.12633411, -1.09337121, -0.05631373],
       [ 1.84941208,  1.40694198, -1.02338533,  0.40211185, -0.23334164],
       [ 0.59818026, -0.94100596, -0.4865875 ,  0.65585595,  0.95265988],
       [-1.72029092, -0.98084182, -0.05350483, -0.04500301,  1.47971807],
       [ 0.16910619, -0.05661535,  1.85083696, -0.30480049, -0.95625902]])

In [79]:
#- Perform element-wise multiplication between two arrays of the same shape.


In [80]:
a=np.random.randint(1,11,(3,4))

In [81]:
a

array([[5, 7, 6, 9],
       [8, 3, 8, 1],
       [8, 4, 6, 3]])

In [82]:
b=np.random.randint(1,11,(3,4))

In [83]:
b

array([[9, 9, 3, 9],
       [1, 3, 7, 7],
       [7, 5, 6, 3]])

In [84]:
result=a*b

In [85]:
result

array([[45, 63, 18, 81],
       [ 8,  9, 56,  7],
       [56, 20, 36,  9]])

In [86]:
#Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).

In [87]:
c=np.array([1,2,34,5])

In [88]:
c

array([ 1,  2, 34,  5])

In [90]:
c/2.54

array([ 0.39370079,  0.78740157, 13.38582677,  1.96850394])

In [91]:
#- Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1

In [94]:
a=np.random.randint(0,9,(1,10))

In [95]:
a

array([[2, 8, 4, 1, 5, 7, 4, 0, 0, 1]])

In [96]:
arr = np.arange(10) #give numbers from 0-10

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr[arr%2!=0]=-1

In [103]:
arr

array([ 0, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [105]:
arr[arr%2!=0]=-1

In [106]:
arr

array([ 0, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [107]:
import numpy as np

# Create a 1D array of numbers from 0 to 9
arr = np.arange(10)

# Replace odd numbers with -1
arr[arr % 2 != 0] = -1



In [108]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [109]:
b=np.arange(10)

In [110]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
b[b%2!=0]=-1

In [112]:
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [113]:
#- Create a 2D array with random values and find the indices of the maximum and minimum values.

In [114]:
c=np.random.randint(1,11,(2,2))

In [115]:
c=np.random.randn(3,4)

In [116]:
c

array([[ 0.51131765,  1.54858606,  0.06471426, -1.52884507],
       [ 0.24017655,  0.31783019,  0.12635808,  1.59317401],
       [-0.93635681, -1.39660882, -0.3557717 , -0.08854122]])

In [117]:
m=np.max(c)

In [118]:
m

1.5931740051945462

In [119]:
c[np.max(c)]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [1]:
import pandas as pd

In [2]:
emp={'name':'Ankit','gender':'male','email':'sourav@gmail.com'}

In [3]:
print(emp)

{'name': 'Ankit', 'gender': 'male', 'email': 'sourav@gmail.com'}


In [4]:
import pandas as pd

In [5]:
emp = {'name':'Ankit', 'gender':'Male', 'email':'ankit@gmail.com'}
emp= {"name":["Ankit","Rahul","Priya"],"gender":["Male","Male","Female"], "email":["ankit@gmail.com","rahul@gmail.com","priya@gmail.com"] }

In [6]:
print(emp)


{'name': ['Ankit', 'Rahul', 'Priya'], 'gender': ['Male', 'Male', 'Female'], 'email': ['ankit@gmail.com', 'rahul@gmail.com', 'priya@gmail.com']}


In [9]:
emp_new=pd.DataFrame(emp)

In [10]:
emp_new

name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com

In [11]:
emp_new['name']

0    Ankit
1    Rahul
2    Priya
Name: name, dtype: object

#we can also access the column name 

In [12]:
emp_new.name

0    Ankit
1    Rahul
2    Priya
Name: name, dtype: object

In [13]:
emp_new.info

<bound method DataFrame.info of     name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com>

In [14]:
emp_new.describe

<bound method NDFrame.describe of     name  gender            email
0  Ankit    Male  ankit@gmail.com
1  Rahul    Male  rahul@gmail.com
2  Priya  Female  priya@gmail.com>

In [15]:
type(emp_new['name'])

pandas.core.series.Series

In [17]:
pd.Series([1,2])

0    1
1    2
dtype: int64

In [18]:
df=pd.read_csv('orders.txt')
df

FileNotFoundError: [Errno 2] No such file or directory: 'orders.txt'

In [19]:
import pandas as pd

In [28]:
df=pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt",delimiter=',')

In [30]:
df.head(5)

order_id  order_date     customer_name           city  \
0  CA-2018-100006  2018-09-07       Dennis Kane  New York City   
1  CA-2018-100090  2018-07-08        Ed Braxton  San Francisco   
2  CA-2018-100293  2018-03-14  Neil Französisch   Jacksonville   
3  CA-2018-100328  2018-01-28   Jasper Cacioppo  New York City   
4  CA-2018-100363  2018-04-08       Jim Mitchum       Glendale   

          category       product_id    sales    profit  
0       Technology  TEC-PH-10002075  377.970  109.6113  
1        Furniture  FUR-TA-10003715  502.488  -87.9354  
2  Office Supplies  OFF-PA-10000176   91.056   31.8696  
3  Office Supplies  OFF-BI-10000343    3.928    1.3257  
4  Office Supplies  OFF-FA-10000611    2.368    0.8288

In [31]:
df.tail(10)

order_id  order_date      customer_name           city  \
4999  US-2021-167570  2021-12-08        Emily Grady   Philadelphia   
5000  US-2021-167920  2021-12-09           John Lee       Richmond   
5001  US-2021-168116  2021-11-04     Grant Thornton     Burlington   
5002  US-2021-168613  2021-10-08        Gary McGarr  New York City   
5003  US-2021-168690  2021-01-07      Thais Sissman   Ormond Beach   
5004  US-2021-168802  2021-11-03      Jack O'Briant        Seattle   
5005  US-2021-169320  2021-07-23     Lena Hernandez        Elkhart   
5006  US-2021-169488  2021-09-07       Allen Armold     Providence   
5007  US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee   
5008  US-2021-169551  2021-07-07          Rob Lucas   Philadelphia   

             category       product_id    sales   profit  
4999        Furniture  FUR-CH-10003396  215.544 -58.5048  
5000  Office Supplies  OFF-AP-10000159  214.900  62.3210  
5001  Office Supplies  OFF-AP-10002457  167.440  14.6510  
5002        Furniture  FUR-CH-10002372  145.764   3.2392  
5003  Office Supplies  OFF-BI-10000145    2.808  -1.9656  
5004  Office Supplies  OFF-BI-10002393   18.368   5.9696  
5005  Office Supplies  OFF-AR-10003602   11.680   5.4896  
5006  Office Supplies  OFF-PA-10000157   39.960  18.7812  
5007  Office Supplies  OFF-AP-10001947   91.600  26.5640  
5008        Furniture  FUR-BO-10001519   87.210 -45.3492

In [37]:
col=['order_id','order_date','category']
df[col]

order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [35]:
df[col]

NameError: name 'col' is not defined

In [38]:
df[['order_id','order_date','category']]

order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [41]:
df.iloc[0,2]

'Dennis Kane'

In [43]:
df.iloc[1:3,0:2]

order_id  order_date
1  CA-2018-100090  2018-07-08
2  CA-2018-100293  2018-03-14

In [46]:
df.iloc[[1,2],[0,2]] #you can pass list for random integers


order_id     customer_name
1  CA-2018-100090        Ed Braxton
2  CA-2018-100293  Neil Französisch

In [50]:
df_emp.loc[0:1,'name']

NameError: name 'df_emp' is not defined

In [51]:
df_emp

NameError: name 'df_emp' is not defined

In [53]:
df.set_index('email')

KeyError: "None of ['email'] are in the columns"

# use orders.txt dataset for below problems

# 2- write a program to find all orders in furniture category with sales amount between 1000 and 1200
# 3- write a program to find all the orders where there was a loss (profit<0) in the city of new york , Los Angeles and Seattle
# 4- write a program to find unique list of cities where orders are placed for Office Supplies category.
# 5- in the new york city how many orders were placed in each of the category 
# 6- set the index of orders dataframe to order_id and fetch order details(all columns) of following list of orders : 
# CA-2019-115742
# CA-2020-111682
# CA-2019-149587
# US-2020-150147
# CA-2020-138520

# 7- for the previous question display columns order id, order date , sales and category columns in the given order

# 8- for the previous(6th) question display all the columns from order_date to city (as per the order in dataset)

# 9- sort the index (order id) in descending order for the dataframe 

# 10- write the result of previous question into a csv file in your local machine


# 1- write a program to fetch all the orders with indexes  multiple of 100 eg : 100,200,300,400..... . 
#-- Display order_id , category and sales columns -->

In [54]:
import pandas as pd

In [55]:
new=pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt",delimiter=',')

In [59]:
df[['order_id' , 'category','sales']] 

order_id         category    sales
0     CA-2018-100006       Technology  377.970
1     CA-2018-100090        Furniture  502.488
2     CA-2018-100293  Office Supplies   91.056
3     CA-2018-100328  Office Supplies    3.928
4     CA-2018-100363  Office Supplies    2.368
...              ...              ...      ...
5004  US-2021-168802  Office Supplies   18.368
5005  US-2021-169320  Office Supplies   11.680
5006  US-2021-169488  Office Supplies   39.960
5007  US-2021-169502  Office Supplies   91.600
5008  US-2021-169551        Furniture   87.210

[5009 rows x 3 columns]

In [71]:
res=df[df.index%100==0]
res[

order_id  order_date        customer_name            city  \
0     CA-2018-100006  2018-09-07          Dennis Kane   New York City   
100   CA-2018-107573  2018-12-12         Philip Brown           Miami   
200   CA-2018-115791  2018-01-16    Delfina Latchford    Philadelphia   
300   CA-2018-124723  2018-08-05        Gary Zandusky      Texas City   
400   CA-2018-132500  2018-09-08        Gary Zandusky   San Francisco   
500   CA-2018-141110  2018-11-26         Luke Schmidt          Fresno   
600   CA-2018-151078  2018-11-12      Roy Französisch     San Antonio   
700   CA-2018-159814  2018-06-24        Liz Pelletier          Tucson   
800   CA-2018-169649  2018-12-09          Thomas Seio         Chicago   
900   CA-2019-107902  2019-08-28       Suzanne McNair       Fairfield   
1000  CA-2019-114811  2019-11-08        Keith Dawkins   New York City   
1100  CA-2019-123092  2019-12-03           Jack Garza    Jacksonville   
1200  CA-2019-130792  2019-04-28    Russell Applegate         Houston   
1300  CA-2019-137708  2019-11-22        Nathan Gelder     Los Angeles   
1400  CA-2019-145324  2019-11-15        Duane Huffman    Harrisonburg   
1500  CA-2019-153388  2019-08-01        Pauline Chand     Los Angeles   
1600  CA-2019-161445  2019-09-07        Corey Catlett          Durham   
1700  CA-2020-100083  2020-11-24         Carol Darley         Medford   
1800  CA-2020-106558  2020-01-17         Dionis Lloyd        Columbus   
1900  CA-2020-113082  2020-09-12       Matt Collister           Utica   
2000  CA-2020-119018  2020-11-04           Carl Weiss     Los Angeles   
2100  CA-2020-125815  2020-10-28    Denise Leinenbach   New York City   
2200  CA-2020-132094  2020-08-26          Vivek Grady    Philadelphia   
2300  CA-2020-138968  2020-03-15           Fred Chung   San Francisco   
2400  CA-2020-145583  2020-10-13       Lena Creighton       Roseville   
2500  CA-2020-152121  2020-11-27       Craig Carreira      Scottsdale   
2600  CA-2020-158099  2020-09-03         Paul Knutson    Philadelphia   
2700  CA-2020-163755  2020-11-04     Alejandro Savely         Seattle   
2800  CA-2021-100111  2021-09-20          Seth Vernon   New York City   
2900  CA-2021-104577  2021-05-12  Chloris Kastensmidt         Everett   
3000  CA-2021-108910  2021-09-24      Kelly Collister          Newark   
3100  CA-2021-115448  2021-11-11   Michelle Huthwaite       Knoxville   
3200  CA-2021-120222  2021-04-25   Lauren Leatherbury     Los Angeles   
3300  CA-2021-124576  2021-08-01     Heather Kirkland         Salinas   
3400  CA-2021-129707  2021-04-25         Larry Hughes        Chandler   
3500  CA-2021-134796  2021-06-25          Fred McMath     Bolingbrook   
3600  CA-2021-140242  2021-05-06           Max Ludwig         Chicago   
3700  CA-2021-144827  2021-12-21         Sanjit Engle      Costa Mesa   
3800  CA-2021-149853  2021-10-03      Patrick O'Brill         Hialeah   
3900  CA-2021-155089  2021-12-02          Daniel Byrd           Tampa   
4000  CA-2021-160325  2021-09-24         Bart Pistole        Lawrence   
4100  CA-2021-165008  2021-09-15       Doug O'Connell  Salt Lake City   
4200  US-2018-103338  2018-03-11      Richard Bierner       Roseville   
4300  US-2018-147648  2018-11-26     Lindsay Shagiari   San Francisco   
4400  US-2019-123218  2019-12-20     Katherine Ducich         Chicago   
4500  US-2019-168732  2019-12-10         Khloe Miller         Roswell   
4600  US-2020-132577  2020-11-22       Jeremy Ellison         Houston   
4700  US-2020-163258  2020-12-29    Phillip Flathmann     Los Angeles   
4800  US-2021-116701  2021-12-17         Logan Currie          Dallas   
4900  US-2021-140074  2021-03-23       Erin Creighton   New York City   
5000  US-2021-167920  2021-12-09             John Lee        Richmond   

             category       product_id     sales    profit  
0          Technology  TEC-PH-10002075   377.970  109.6113  
100   Office Supplies  OFF-EN-10001099    23.472    7.6284  
200         Furniture  FUR-FU-10

In [74]:
res[['order_id' , 'category','sales']] 

order_id         category     sales
0     CA-2018-100006       Technology   377.970
100   CA-2018-107573  Office Supplies    23.472
200   CA-2018-115791        Furniture   127.104
300   CA-2018-124723        Furniture   489.230
400   CA-2018-132500       Technology    49.980
500   CA-2018-141110  Office Supplies    40.540
600   CA-2018-151078  Office Supplies    49.632
700   CA-2018-159814        Furniture     4.272
800   CA-2018-169649  Office Supplies    20.388
900   CA-2019-107902  Office Supplies   470.360
1000  CA-2019-114811        Furniture   577.764
1100  CA-2019-123092        Furniture    77.952
1200  CA-2019-130792  Office Supplies     8.652
1300  CA-2019-137708  Office Supplies    37.940
1400  CA-2019-145324        Furniture    39.960
1500  CA-2019-153388        Furniture  1004.976
1600  CA-2019-161445  Office Supplies   140.736
1700  CA-2020-100083  Office Supplies    24.784
1800  CA-2020-106558       Technology   316.000
1900  CA-2020-113082        Furniture    40.480
2000  CA-2020-119018  Office Supplies     4.176
2100  CA-2020-125815  Office Supplies    12.420
2200  CA-2020-132094  Office Supplies     5.472
2300  CA-2020-138968        Furniture  1352.032
2400  CA-2020-145583        Furniture    43.120
2500  CA-2020-152121       Technology   271.992
2600  CA-2020-158099  Office Supplies  1141.470
2700  CA-2020-163755        Furniture   209.880
2800  CA-2021-100111        Furniture  2254.410
2900  CA-2021-104577  Office Supplies    87.600
3000  CA-2021-108910        Furniture   103.056
3100  CA-2021-115448        Furniture    88.920
3200  CA-2021-120222  Office Supplies    73.344
3300  CA-2021-124576  Office Supplies    54.896
3400  CA-2021-129707  Office Supplies     8.896
3500  CA-2021-134796       Technology   148.480
3600  CA-2021-140242  Office Supplies     6.408
3700  CA-2021-144827  Office Supplies   124.360
3800  CA-2021-149853  Office Supplies    17.920
3900  CA-2021-155089  Office Supplies    45.660
4000  CA-2021-160325       Technology   391.980
4100  CA-2021-165008  Office Supplies   295.056
4200  US-2018-103338  Office Supplies     7.980
4300  US-2018-147648  Office Supplies    81.980
4400  US-2019-123218        Furniture   359.058
4500  US-2019-168732  Office Supplies     1.780
4600  US-2020-132577  Office Supplies    23.616
4700  US-2020-163258  Office Supplies    11.232
4800  US-2021-116701  Office Supplies    66.284
4900  US-2021-140074  Office Supplies    25.680
5000  US-2021-167920  Office Supplies   214.900

# 2- write a program to find all orders in furniture category with sales amount between 1000 and 1200

In [78]:
fc=(new['category']=='Furniture' ) & (new['sales']>=1000) & (new['sales']<=1200)
new[fc]

order_id  order_date           customer_name           city  \
155   CA-2018-111871  2018-03-18           Eileen Kiefer  San Francisco   
374   CA-2018-130428  2018-03-31            Trudy Glocke          Tampa   
631   CA-2018-153913  2018-12-16               Ken Black        Hialeah   
834   CA-2019-102582  2019-09-15          Natalie Webber         Mobile   
890   CA-2019-106320  2019-09-25             Emily Burns           Orem   
924   CA-2019-110016  2019-11-29              Bill Tyler        Detroit   
1084  CA-2019-121720  2019-06-11                 Jim Epp       Lakeland   
1120  CA-2019-124891  2019-07-31             Rick Hansen  New York City   
1155  CA-2019-127509  2019-11-09      Adam Shillingsburg    Springfield   
1205  CA-2019-130890  2019-11-02           Jas O'Carroll    Los Angeles   
1500  CA-2019-153388  2019-08-01           Pauline Chand    Los Angeles   
1504  CA-2019-153549  2019-03-29          Sara Luxemburg   Jacksonville   
1737  CA-2020-102092  2020-12-09          Paul MacIntyre    Springfield   
1950  CA-2020-115917  2020-05-20            Rick Bensley        Vallejo   
1965  CA-2020-116911  2020-09-15        Justin Deggeller     Twin Falls   
2069  CA-2020-123946  2020-09-12         Anthony Johnson    Springfield   
2202  CA-2020-132304  2020-06-14          Anthony Rawles        Seattle   
2263  CA-2020-136406  2020-04-15          Bill Donatelli  San Francisco   
2360  CA-2020-142958  2020-12-13            Rob Williams       Torrance   
2505  CA-2020-152289  2020-08-26          Linda Cazamias       Pasadena   
2561  CA-2020-155516  2020-10-21         Michael Kennedy     Manchester   
2856  CA-2021-102379  2021-12-02           Brenda Bowman        Oakland   
3102  CA-2021-115602  2021-12-18             Doug Jacobs  New York City   
3150  CA-2021-117702  2021-11-28        Lindsay Shagiari      Baltimore   
3326  CA-2021-126067  2021-08-28           Kristina Nunn        Seattle   
3644  CA-2021-142342  2021-07-17         Anthony Johnson   Apple Valley   
3689  CA-2021-144491  2021-03-27         Caroline Jumper        Houston   
4238  US-2018-117968  2018-08-05         Ricardo Sperren        Meriden   
4251  US-2018-123183  2018-11-19       Georgia Rosenberg     Wilmington   
4254  US-2018-125521  2018-03-14      Christine Kargatis     Chesapeake   
4279  US-2018-137869  2018-03-28  Christina VanderZanden     Des Moines   
4299  US-2018-147627  2018-01-20            Hunter Lopez      Jonesboro   
4304  US-2018-148838  2018-03-17          Christine Phan  New York City   
4423  US-2019-134558  2019-12-19             Peter McVee          Dover   
4471  US-2019-157154  2019-01-10           Michael Moore  New York City   
4713  US-2020-167339  2020-01-21           Tamara Dahlen      San Diego   
4733  US-2021-102890  2021-06-30            Sheri Gordon  New York City   
4773  US-2021-110576  2021-11-28              Ross Baird   Philadelphia   
4985  US-2021-164056  2021-04-29           Filia McAdams         Dublin   
4989  US-2021-165456  2021-11-30             Trudy Brown   Philadelphia   

       category       product_id     sales    profit  
155   Furniture  FUR-BO-10004218  1198.330   70.4900  
374   Furniture  FUR-CH-10002965  1125.488   98.4802  
631   Furniture  FUR-CH-10000988  1013.832  101.3832  
834   Furniture  FUR-CH-10004853  1056.860  306.4894  
890   Furniture  FUR-TA-10000577  1044.630  240.2649  
924   Furniture  FUR-CH-10002880  1106.910  121.7601  
1084  Furniture  FUR-CH-10003312  1123.920 -182.6370  
1120  Furniture  FUR-TA-10002903  1090.782 -290.8752  
1155  Furniture  FUR-TA-10002855  1024.380  215.1198  
1205  Furniture  FUR-TA-10002903  1038.840   51.9420  
1500  Furniture  FUR-TA-10003715  1004.976 -175.8708  
1504  Furniture  FUR-CH-10004086  1166.920  131.2785  
1737  Furniture  FUR-TA-10002530  1056.860  158.5290  
1950  Furniture  FUR-FU-10000576  1049.200  272.7920  
1965  Furniture  FUR-TA-10003473  1128.390  259.5297  
2069  Furniture  FUR-CH-10002073  1059.120  307.1448  
2

3- write a program to find all the orders where there was a loss (profit<0) in the city of new york , Los Angeles and Seattle



In [83]:
new['profit']<0
places=['New York','Los Angeles','Seattle']
fc=(new['city'].isin(places)) & (new['profit']<0)
new[fc]

order_id  order_date       customer_name         city    category  \
27    CA-2018-101931  2018-10-28        Todd Sumrall  Los Angeles   Furniture   
87    CA-2018-106439  2018-10-31        Greg Guthrie  Los Angeles   Furniture   
315   CA-2018-125829  2018-11-04       William Brown  Los Angeles   Furniture   
763   CA-2018-166471  2018-08-09   Matthew Grinstein      Seattle  Technology   
832   CA-2019-102316  2019-03-01       Dave Hallsten  Los Angeles   Furniture   
889   CA-2019-106257  2019-04-13      Eugene Barchas  Los Angeles   Furniture   
1215  CA-2019-131597  2019-09-14    Stefania Perrino  Los Angeles   Furniture   
1447  CA-2019-149083  2019-09-25       Sally Hughsby      Seattle   Furniture   
1500  CA-2019-153388  2019-08-01       Pauline Chand  Los Angeles   Furniture   
1527  CA-2019-154970  2019-01-05       Steven Roelle      Seattle   Furniture   
1905  CA-2020-113243  2020-06-10         Olvera Toch  Los Angeles   Furniture   
1940  CA-2020-114972  2020-11-03   Phillip Flathmann  Los Angeles   Furniture   
2086  CA-2020-124793  2020-03-14  Muhammed MacIntyre      Seattle   Furniture   
2162  CA-2020-129868  2020-12-26         Mike Caudle  Los Angeles   Furniture   
2247  CA-2020-135265  2020-07-07  Christopher Conant  Los Angeles   Furniture   
2351  CA-2020-142398  2020-04-12          Beth Paige  Los Angeles   Furniture   
2483  CA-2020-150350  2020-08-23    Maxwell Schwartz      Seattle   Furniture   
2619  CA-2020-159009  2020-09-23        Dave Poirier      Seattle   Furniture   
2698  CA-2020-163594  2020-04-12      Jason Fortune-  Los Angeles   Furniture   
2721  CA-2020-164889  2020-06-03      Christine Phan  Los Angeles   Furniture   
2865  CA-2021-102750  2021-09-04        Greg Maxwell  Los Angeles   Furniture   
2908  CA-2021-104850  2021-06-13   Tamara Willingham      Seattle   Furniture   
2957  CA-2021-107174  2021-11-06     Adam Bellavance      Seattle   Furniture   
3036  CA-2021-111388  2021-09-02  Stephanie Ulpright      Seattle   Furniture   
3144  CA-2021-117513  2021-03-03          Bill Tyler  Los Angeles   Furniture   
3179  CA-2021-118885  2021-12-29        James Galang  Los Angeles   Furniture   
3277  CA-2021-123085  2021-03-03           Ed Jacobs  Los Angeles   Furniture   
3389  CA-2021-128965  2021-04-17        Pamela Stobb  Los Angeles   Furniture   
3555  CA-2021-137498  2021-09-09        Liz Carlisle  Los Angeles   Furniture   
3559  CA-2021-137624  2021-11-10       Maria Etezadi  Los Angeles   Furniture   
3617  CA-2021-140963  2021-06-10       Michelle Tran  Los Angeles   Furniture   
4134  CA-2021-167003  2021-05-23    Vivek Sundaresam  Los Angeles   Furniture   
4578  US-2020-125969  2020-11-06    Lindsay Shagiari  Los Angeles   Furniture   
4728  US-2021-101784  2021-07-06     Patrick O'Brill  Los Angeles   Furniture   
4982  US-2021-163300  2021-09-15         Erica Smith  Los Angeles   Furniture   
4983  US-2021-163657  2021-09-02           Janet Lee  Los Angeles   Furniture   

           product_id     sales    profit  
27    FUR-BO-10001337   616.998  -36.2940  
87    FUR-CH-10003833   146.352   -9.1470  
315   FUR-TA-10002041   573.728  -64.5444  
763   TEC-PH-10000038   219.168  -43.8336  
832   FUR-CH-10003396   184.752  -20.7846  
889   FUR-TA-10002530   241.568  -15.0980  
1215  FUR-TA-10002607   170.136   -8.5068  
1447  FUR-CH-10004289   307.136  -11.5176  
1500  FUR-TA-10003715  1004.976 -175.8708  
1527  FUR-CH-10003396    61.584   -6.9282  
1905  FUR-TA-10004256  1335.680 -217.0480  
1940  FUR-CH-10001190   217.584  -29.9178  
2086  FUR-CH-10002880   196.784  -22.1382  
2162  FUR-CH-10003535   146.352   -5.4882  
2247  FUR-CH-10003061   287.968   -3.5996  
2351  FUR-CH-10001545   638.288  -31.9144  
2483  FUR-CH-10001973   532.704  -39.9528  
2619  FUR-CH-10003396   184.752  -20.7846  
2698  FUR-CH-10000225   194.352  -36.4410  
2721  FUR-TA-10001676    71.088   -1.7772  
2865  FUR-TA-10000198  1322.352  -99.1764  
2908  FUR-CH-10003774   291.136  -25.4744  
29

# write a program to find unique list of cities where orders are placed for Office Supplies category.


In [84]:
new['city'].unique()

array(['New York City', 'San Francisco', 'Jacksonville', 'Glendale',
       'Houston', 'Springfield', 'Jackson', 'Pomona', 'Lakewood',
       'Albuquerque', 'Roswell', 'Newport News', 'Salt Lake City',
       'Chicago', 'Mesa', 'Seattle', 'Philadelphia', 'Los Angeles',
       'New Rochelle', 'Columbia', 'El Paso', 'Miami', 'Richmond',
       'Sacramento', 'Brentwood', 'Las Vegas', 'Charlotte', 'Alexandria',
       'Indianapolis', 'San Jose', 'Palm Coast', 'Newark', 'Cleveland',
       'Huntsville', 'Mount Vernon', 'Fairfield', 'Sandy Springs',
       'Fort Worth', 'Lakeland', 'Southaven', 'Orem', 'Laredo',
       'San Diego', 'Escondido', 'Provo', 'Pasadena', 'Madison',
       'Columbus', 'Athens', 'Aurora', 'Gilbert', 'Bowling Green',
       'Billings', 'Cottage Grove', 'Saint Petersburg', 'Buffalo Grove',
       'Lawrence', 'Plainfield', 'Linden', 'Garden City', 'Memphis',
       'Pasco', 'Oceanside', 'Long Beach', 'Romeoville', 'Tempe',
       'Lorain', 'Fort Lauderdale', 'Hollywood

In [85]:
new

order_id  order_date      customer_name           city  \
0     CA-2018-100006  2018-09-07        Dennis Kane  New York City   
1     CA-2018-100090  2018-07-08         Ed Braxton  San Francisco   
2     CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville   
3     CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City   
4     CA-2018-100363  2018-04-08        Jim Mitchum       Glendale   
...              ...         ...                ...            ...   
5004  US-2021-168802  2021-11-03      Jack O'Briant        Seattle   
5005  US-2021-169320  2021-07-23     Lena Hernandez        Elkhart   
5006  US-2021-169488  2021-09-07       Allen Armold     Providence   
5007  US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee   
5008  US-2021-169551  2021-07-07          Rob Lucas   Philadelphia   

             category       product_id    sales    profit  
0          Technology  TEC-PH-10002075  377.970  109.6113  
1           Furniture  FUR-TA-10003715  502.488  -87.9354  
2     Office Supplies  OFF-PA-10000176   91.056   31.8696  
3     Office Supplies  OFF-BI-10000343    3.928    1.3257  
4     Office Supplies  OFF-FA-10000611    2.368    0.8288  
...               ...              ...      ...       ...  
5004  Office Supplies  OFF-BI-10002393   18.368    5.9696  
5005  Office Supplies  OFF-AR-10003602   11.680    5.4896  
5006  Office Supplies  OFF-PA-10000157   39.960   18.7812  
5007  Office Supplies  OFF-AP-10001947   91.600   26.5640  
5008        Furniture  FUR-BO-10001519   87.210  -45.3492  

[5009 rows x 8 columns]

In [94]:
office_supplies=new[new['category']=='Office Supplies']
office_supplies['city'].unique()
# write a program to find unique list of cities where orders are placed for Office Supplies category.


array(['Jacksonville', 'New York City', 'Glendale', 'Jackson', 'Pomona',
       'Roswell', 'Salt Lake City', 'Chicago', 'Mesa', 'Springfield',
       'Seattle', 'Philadelphia', 'Miami', 'Richmond', 'Brentwood',
       'Las Vegas', 'Charlotte', 'Alexandria', 'Indianapolis',
       'San Francisco', 'Huntsville', 'Mount Vernon', 'Fairfield',
       'El Paso', 'Houston', 'Sandy Springs', 'Laredo', 'San Diego',
       'Escondido', 'Provo', 'Pasadena', 'Madison', 'Athens', 'Gilbert',
       'Bowling Green', 'Billings', 'Los Angeles', 'Cottage Grove',
       'Lawrence', 'Columbus', 'Plainfield', 'Long Beach', 'Romeoville',
       'Tempe', 'Fort Lauderdale', 'Hollywood', 'Newark', 'Lakewood',
       'Santa Clara', 'Brownsville', 'Great Falls', 'Columbia', 'Akron',
       'Little Rock', 'Arlington', 'Naperville', 'Chula Vista',
       'Rock Hill', 'Rochester', 'Hempstead', 'Logan', 'Lancaster',
       'Cincinnati', 'Sioux Falls', 'Johnson City', 'Minneapolis',
       'Margate', 'Virginia Beach'


5- in the new york city how many orders were placed in each of the category 

In [99]:
res=new[new['city']=='New York City']
res

order_id  order_date       customer_name           city  \
0     CA-2018-100006  2018-09-07         Dennis Kane  New York City   
3     CA-2018-100328  2018-01-28     Jasper Cacioppo  New York City   
5     CA-2018-100391  2018-05-25       Barry Weirich  New York City   
18    CA-2018-101364  2018-12-22   Tamara Willingham  New York City   
26    CA-2018-101833  2018-11-17     Frank Gastineau  New York City   
...              ...         ...                 ...            ...   
4934  US-2021-148866  2021-09-19      Jessica Myrick  New York City   
4956  US-2021-155866  2021-11-17  Christopher Conant  New York City   
4962  US-2021-157896  2021-11-16    Christy Brittain  New York City   
4991  US-2021-166037  2021-01-28        Craig Leslie  New York City   
5002  US-2021-168613  2021-10-08         Gary McGarr  New York City   

             category       product_id    sales    profit  
0          Technology  TEC-PH-10002075  377.970  109.6113  
3     Office Supplies  OFF-BI-10000343    3.928    1.3257  
5     Office Supplies  OFF-PA-10001471   14.620    6.7252  
18    Office Supplies  OFF-BI-10003984  296.712  100.1403  
26    Office Supplies  OFF-PA-10003591   34.440   17.2200  
...               ...              ...      ...       ...  
4934  Office Supplies  OFF-PA-10004782   32.400   15.5520  
4956        Furniture  FUR-FU-10004091  187.760   76.9816  
4962  Office Supplies  OFF-PA-10004092  146.820   73.4100  
4991       Technology  TEC-AC-10002800  449.910  157.4685  
5002        Furniture  FUR-CH-10002372  145.764    3.2392  

[450 rows x 8 columns]

In [100]:
res['category'].value_counts()

category
Office Supplies    257
Furniture          157
Technology          36
Name: count, dtype: int64

6- set the index of orders dataframe to order_id and fetch order details(all columns) of following list of orders : 
CA-2019-115742
CA-2020-111682
CA-2019-149587
US-2020-150147
CA-2020-138520



In [115]:
result=new.set_index('order_id',inplace=True)

In [112]:
result

order_date      customer_name           city         category  \
order_id                                                                        
CA-2018-100006  2018-09-07        Dennis Kane  New York City       Technology   
CA-2018-100090  2018-07-08         Ed Braxton  San Francisco        Furniture   
CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville  Office Supplies   
CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City  Office Supplies   
CA-2018-100363  2018-04-08        Jim Mitchum       Glendale  Office Supplies   
...                    ...                ...            ...              ...   
US-2021-168802  2021-11-03      Jack O'Briant        Seattle  Office Supplies   
US-2021-169320  2021-07-23     Lena Hernandez        Elkhart  Office Supplies   
US-2021-169488  2021-09-07       Allen Armold     Providence  Office Supplies   
US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee  Office Supplies   
US-2021-169551  2021-07-07          Rob Lucas   Philadelphia        Furniture   

                     product_id    sales    profit  
order_id                                            
CA-2018-100006  TEC-PH-10002075  377.970  109.6113  
CA-2018-100090  FUR-TA-10003715  502.488  -87.9354  
CA-2018-100293  OFF-PA-10000176   91.056   31.8696  
CA-2018-100328  OFF-BI-10000343    3.928    1.3257  
CA-2018-100363  OFF-FA-10000611    2.368    0.8288  
...                         ...      ...       ...  
US-2021-168802  OFF-BI-10002393   18.368    5.9696  
US-2021-169320  OFF-AR-10003602   11.680    5.4896  
US-2021-169488  OFF-PA-10000157   39.960   18.7812  
US-2021-169502  OFF-AP-10001947   91.600   26.5640  
US-2021-169551  FUR-BO-10001519   87.210  -45.3492  

[5009 rows x 7 columns]

In [125]:
col=['CA-2019-115742','CA-2020-111682','CA-2019-149587','US-2020-150147','CA-2020-138520']
result.loc[col]

AttributeError: 'NoneType' object has no attribute 'loc'

In [119]:
output

NameError: name 'output' is not defined

In [127]:
df = pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt", delimiter=',')

# Set the index of the DataFrame to 'order_id'
df.set_index('order_id', inplace=True)

# List of orders to fetch details for
order_list = ['CA-2019-115742', 'CA-2020-111682', 'CA-2019-149587', 'US-2020-150147', 'CA-2020-138520']

# Fetch order details for the specified list of orders
order_details = df.loc[order_list]

# Display the order details
print(order_details)


                order_date    customer_name           city         category  \
order_id                                                                      
CA-2019-115742  2019-04-18    Darren Powers     New Albany        Furniture   
CA-2020-111682  2020-06-17  Ted Butterfield           Troy        Furniture   
CA-2019-149587  2019-01-31       Karl Braun    Minneapolis        Furniture   
US-2020-150147  2020-04-25       John Lucas   Philadelphia  Office Supplies   
CA-2020-138520  2020-04-08  Jeremy Lonsdale  New York City        Furniture   

                     product_id    sales   profit  
order_id                                           
CA-2019-115742  FUR-CH-10003061   89.990  17.0981  
CA-2020-111682  FUR-CH-10003968  319.410   7.0980  
CA-2019-149587  FUR-FU-10003799   53.340  16.5354  
US-2020-150147  OFF-BI-10001153   20.724 -13.8160  
CA-2020-138520  FUR-BO-10002268  388.704  -4.8588  


In [129]:

#7- for the previous question display columns order id, order date , sales and category columns in the given order


In [131]:
df = pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt", delimiter=',')

# Set the index of the DataFrame to 'order_id'
df.set_index('order_id', inplace=True)

# List of orders to fetch details for
order_list = ['CA-2019-115742', 'CA-2020-111682', 'CA-2019-149587', 'US-2020-150147', 'CA-2020-138520']

# Fetch order details for the specified list of orders
order_details = df.loc[order_list,['order_date' , 'sales','category']]

# Display the order details
print(order_details)



                order_date    sales         category
order_id                                            
CA-2019-115742  2019-04-18   89.990        Furniture
CA-2020-111682  2020-06-17  319.410        Furniture
CA-2019-149587  2019-01-31   53.340        Furniture
US-2020-150147  2020-04-25   20.724  Office Supplies
CA-2020-138520  2020-04-08  388.704        Furniture


In [134]:
# 8- for the previous(6th) question display all the columns from order_date to city (as per the order in dataset)
df = pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt", delimiter=',')

# Set the index of the DataFrame to 'order_id'
df.set_index('order_id', inplace=True)

# List of orders to fetch details for
order_list = ['CA-2019-115742', 'CA-2020-111682', 'CA-2019-149587', 'US-2020-150147', 'CA-2020-138520']

# Fetch order details for the specified list of orders
order_details = df.loc[order_list,'order_date':'city']

# Display the order details
print(order_details)


                order_date    customer_name           city
order_id                                                  
CA-2019-115742  2019-04-18    Darren Powers     New Albany
CA-2020-111682  2020-06-17  Ted Butterfield           Troy
CA-2019-149587  2019-01-31       Karl Braun    Minneapolis
US-2020-150147  2020-04-25       John Lucas   Philadelphia
CA-2020-138520  2020-04-08  Jeremy Lonsdale  New York City


In [139]:
#9- sort the index (order id) in descending order for the dataframe 
import pandas as pd
df=pd.read_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/orders.txt", delimiter=',')
df.set_index('order_id', inplace=True)
df.sort_index(ascending=False,inplace=True)
df


order_date      customer_name           city         category  \
order_id                                                                        
US-2021-169551  2021-07-07          Rob Lucas   Philadelphia        Furniture   
US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee  Office Supplies   
US-2021-169488  2021-09-07       Allen Armold     Providence  Office Supplies   
US-2021-169320  2021-07-23     Lena Hernandez        Elkhart  Office Supplies   
US-2021-168802  2021-11-03      Jack O'Briant        Seattle  Office Supplies   
...                    ...                ...            ...              ...   
CA-2018-100363  2018-04-08        Jim Mitchum       Glendale  Office Supplies   
CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City  Office Supplies   
CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville  Office Supplies   
CA-2018-100090  2018-07-08         Ed Braxton  San Francisco        Furniture   
CA-2018-100006  2018-09-07        Dennis Kane  New York City       Technology   

                     product_id    sales    profit  
order_id                                            
US-2021-169551  FUR-BO-10001519   87.210  -45.3492  
US-2021-169502  OFF-AP-10001947   91.600   26.5640  
US-2021-169488  OFF-PA-10000157   39.960   18.7812  
US-2021-169320  OFF-AR-10003602   11.680    5.4896  
US-2021-168802  OFF-BI-10002393   18.368    5.9696  
...                         ...      ...       ...  
CA-2018-100363  OFF-FA-10000611    2.368    0.8288  
CA-2018-100328  OFF-BI-10000343    3.928    1.3257  
CA-2018-100293  OFF-PA-10000176   91.056   31.8696  
CA-2018-100090  FUR-TA-10003715  502.488  -87.9354  
CA-2018-100006  TEC-PH-10002075  377.970  109.6113  

[5009 rows x 7 columns]

In [144]:
# 10- write the result of previous question into a csv file in your local machine
df.to_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/output.txt")

PermissionError: [Errno 13] Permission denied: 'C:/Program Files/JetBrains/PyCharm 2023.3.4/output.txt'

In [141]:
df

order_date      customer_name           city         category  \
order_id                                                                        
US-2021-169551  2021-07-07          Rob Lucas   Philadelphia        Furniture   
US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee  Office Supplies   
US-2021-169488  2021-09-07       Allen Armold     Providence  Office Supplies   
US-2021-169320  2021-07-23     Lena Hernandez        Elkhart  Office Supplies   
US-2021-168802  2021-11-03      Jack O'Briant        Seattle  Office Supplies   
...                    ...                ...            ...              ...   
CA-2018-100363  2018-04-08        Jim Mitchum       Glendale  Office Supplies   
CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City  Office Supplies   
CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville  Office Supplies   
CA-2018-100090  2018-07-08         Ed Braxton  San Francisco        Furniture   
CA-2018-100006  2018-09-07        Dennis Kane  New York City       Technology   

                     product_id    sales    profit  
order_id                                            
US-2021-169551  FUR-BO-10001519   87.210  -45.3492  
US-2021-169502  OFF-AP-10001947   91.600   26.5640  
US-2021-169488  OFF-PA-10000157   39.960   18.7812  
US-2021-169320  OFF-AR-10003602   11.680    5.4896  
US-2021-168802  OFF-BI-10002393   18.368    5.9696  
...                         ...      ...       ...  
CA-2018-100363  OFF-FA-10000611    2.368    0.8288  
CA-2018-100328  OFF-BI-10000343    3.928    1.3257  
CA-2018-100293  OFF-PA-10000176   91.056   31.8696  
CA-2018-100090  FUR-TA-10003715  502.488  -87.9354  
CA-2018-100006  TEC-PH-10002075  377.970  109.6113  

[5009 rows x 7 columns]

In [149]:
df.to_csv("C:/Program Files/JetBrains/PyCharm 2023.3.4/output.txt")

PermissionError: [Errno 13] Permission denied: 'C:/Program Files/JetBrains/PyCharm 2023.3.4/output.txt'

In [146]:
df

order_date      customer_name           city         category  \
order_id                                                                        
US-2021-169551  2021-07-07          Rob Lucas   Philadelphia        Furniture   
US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee  Office Supplies   
US-2021-169488  2021-09-07       Allen Armold     Providence  Office Supplies   
US-2021-169320  2021-07-23     Lena Hernandez        Elkhart  Office Supplies   
US-2021-168802  2021-11-03      Jack O'Briant        Seattle  Office Supplies   
...                    ...                ...            ...              ...   
CA-2018-100363  2018-04-08        Jim Mitchum       Glendale  Office Supplies   
CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City  Office Supplies   
CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville  Office Supplies   
CA-2018-100090  2018-07-08         Ed Braxton  San Francisco        Furniture   
CA-2018-100006  2018-09-07        Dennis Kane  New York City       Technology   

                     product_id    sales    profit  
order_id                                            
US-2021-169551  FUR-BO-10001519   87.210  -45.3492  
US-2021-169502  OFF-AP-10001947   91.600   26.5640  
US-2021-169488  OFF-PA-10000157   39.960   18.7812  
US-2021-169320  OFF-AR-10003602   11.680    5.4896  
US-2021-168802  OFF-BI-10002393   18.368    5.9696  
...                         ...      ...       ...  
CA-2018-100363  OFF-FA-10000611    2.368    0.8288  
CA-2018-100328  OFF-BI-10000343    3.928    1.3257  
CA-2018-100293  OFF-PA-10000176   91.056   31.8696  
CA-2018-100090  FUR-TA-10003715  502.488  -87.9354  
CA-2018-100006  TEC-PH-10002075  377.970  109.6113  

[5009 rows x 7 columns]

In [150]:
df.to_csv('sorted_orders.csv')


In [151]:
df

order_date      customer_name           city         category  \
order_id                                                                        
US-2021-169551  2021-07-07          Rob Lucas   Philadelphia        Furniture   
US-2021-169502  2021-08-28  Matthew Grinstein      Milwaukee  Office Supplies   
US-2021-169488  2021-09-07       Allen Armold     Providence  Office Supplies   
US-2021-169320  2021-07-23     Lena Hernandez        Elkhart  Office Supplies   
US-2021-168802  2021-11-03      Jack O'Briant        Seattle  Office Supplies   
...                    ...                ...            ...              ...   
CA-2018-100363  2018-04-08        Jim Mitchum       Glendale  Office Supplies   
CA-2018-100328  2018-01-28    Jasper Cacioppo  New York City  Office Supplies   
CA-2018-100293  2018-03-14   Neil Französisch   Jacksonville  Office Supplies   
CA-2018-100090  2018-07-08         Ed Braxton  San Francisco        Furniture   
CA-2018-100006  2018-09-07        Dennis Kane  New York City       Technology   

                     product_id    sales    profit  
order_id                                            
US-2021-169551  FUR-BO-10001519   87.210  -45.3492  
US-2021-169502  OFF-AP-10001947   91.600   26.5640  
US-2021-169488  OFF-PA-10000157   39.960   18.7812  
US-2021-169320  OFF-AR-10003602   11.680    5.4896  
US-2021-168802  OFF-BI-10002393   18.368    5.9696  
...                         ...      ...       ...  
CA-2018-100363  OFF-FA-10000611    2.368    0.8288  
CA-2018-100328  OFF-BI-10000343    3.928    1.3257  
CA-2018-100293  OFF-PA-10000176   91.056   31.8696  
CA-2018-100090  FUR-TA-10003715  502.488  -87.9354  
CA-2018-100006  TEC-PH-10002075  377.970  109.6113  

[5009 rows x 7 columns]